export const STRINGS = {
  app: {
    name: 'Buzz',
    tagline: 'Join the Hive. Get paid to buzz.',
  },
  auth: {
    title: 'Get Paid to Buzz.',
    subtitle:
      'Pick a Hive, make a 30-second video, post on your socials, get paid based on views.',
    phoneLabel: 'Phone number',
    phonePlaceholder: '+1 (555) 000-0000',
    sendCode: 'Send Code',
    verifyTitle: 'Check your texts',
    verifySubtitle: 'We sent a 6-digit code to',
    verifyPlaceholder: '000000',
    verifyButton: 'Verify',
    resend: 'Resend code',
    orContinueWith: 'or continue with',
    continueApple: 'Continue with Apple',
    continueGoogle: 'Continue with Google',
    agree: 'By continuing you agree to our Terms & Privacy Policy',
  },
  home: {
    balanceLabel: 'Available',
    hives: 'Active Hives',
    inspiration: 'Inspiration',
    addSocials: 'Link your socials to start buzzing',
    addSocialsAction: 'Connect',
    noHives: 'No active Hives right now.',
    noHivesSubtitle: 'New Hives join every week. Check back soon.',
    emptyEarnings: 'No buzz yet. Pick a Hive and start earning.',
  },
  hive: {
    verified: 'Hive Verified',
    download: 'Download App',
    submit: 'Buzz for this Hive',
    about: 'About this Hive',
    earnings: 'What you can earn',
    rules: 'Rules & Requirements',
    inspiration: 'Inspiration',
    baseLabel: 'Base',
    perThousand: '/1k views',
    viewMin: 'min. views to qualify',
    cpmOnly: 'Views only',
  },
  submissions: {
    title: 'Your Buzz',
    empty: 'No buzz yet. Pick a Hive and start earning.',
    views: 'views',
    statusPending: 'Pending review',
    statusApproved: 'Approved',
    statusRejected: 'Rejected',
    statusPaid: 'Paid out',
  },
  submit: {
    title: 'Buzz for',
    pickType: 'What type of content is this?',
    urlLabel: 'Post URL',
    urlPlaceholder: 'https://www.tiktok.com/@you/video/...',
    screenshotHint: 'Paste your post link above. Screenshot your analytics and upload as a backup.',
    submitButton: 'Submit Buzz',
    submitted: "You're buzzing.",
    submittedSubtitle:
      "We'll verify your views and add earnings within 24 hours.",
    backToSubmissions: 'Back to Your Buzz',
  },
  profile: {
    title: 'Profile',
    tiers: {
      worker: 'Worker',
      drone: 'Drone',
      queen: 'Queen',
    },
    tierProgress: 'to next tier',
    totalEarned: 'Total Earned',
    totalViews: 'Total Views',
    campaigns: 'Campaigns',
    linkedAccounts: 'Linked Accounts',
    tiktok: 'TikTok',
    instagram: 'Instagram',
    youtube: 'YouTube',
    payouts: 'Payout Settings',
    setupStripe: 'Set Up Payouts',
    stripeConnected: 'Payouts Connected',
    payoutHistory: 'Payout History',
    signOut: 'Sign Out',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'No internet connection.',
    invalidPhone: 'Enter a valid phone number.',
    invalidCode: 'Invalid code. Please try again.',
    invalidUrl: 'Enter a valid TikTok, Instagram, or YouTube URL.',
  },
};
