export const STRINGS = {
  app: {
    name: 'Buzz',
    tagline: 'Clip. Post. Get Paid.',
  },
  auth: {
    title: 'Get Paid to Post.',
    subtitle: 'Clip brand content, post it, earn per 1,000 views.',
    phoneLabel: 'Phone number',
    phonePlaceholder: '+1 (555) 000-0000',
    sendCode: 'Send Code',
    verifyTitle: 'Check your texts',
    verifySubtitle: "We sent a 6-digit code to",
    verifyPlaceholder: '000000',
    verifyButton: 'Verify',
    resend: 'Resend code',
    orContinueWith: 'or continue with',
    continueApple: 'Continue with Apple',
    continueGoogle: 'Continue with Google',
    agree: 'By continuing you agree to our Terms & Privacy Policy',
  },
  home: {
    greeting: 'Ready to earn?',
    lifetimeEarnings: 'Lifetime Earnings',
    pendingEarnings: 'Pending',
    available: 'Available',
    startClipping: 'Start Clipping',
    activeCampaigns: 'Active Campaigns',
    recentActivity: 'Recent Activity',
    noActivity: "You haven't submitted any clips yet.",
    noActivityCta: 'Browse campaigns to get started.',
  },
  campaigns: {
    title: 'Campaigns',
    cpm: 'per 1K views',
    budgetLeft: 'budget left',
    timeLeft: 'left',
    clip: 'Clip This',
    ended: 'Ended',
    paused: 'Paused',
    noCampaigns: 'No active campaigns right now.',
    noCampaignsSubtitle: 'Check back soon — new drops every week.',
  },
  clipping: {
    generating: 'Generating your clips...',
    generatingSubtitle: 'Our AI is cutting the best moments.',
    selectClips: 'Select clips to post',
    selectHint: 'Pick your favorites — you can post multiple.',
    postTo: 'Post to TikTok or Instagram',
    download: 'Download',
    share: 'Share',
    submit: 'I posted it — submit for review',
  },
  submit: {
    title: 'Submit your post',
    subtitle: 'Paste the link to your TikTok or Instagram post.',
    urlLabel: 'Post URL',
    urlPlaceholder: 'https://www.tiktok.com/@you/video/...',
    submitButton: 'Submit',
    submitted: 'Submitted!',
    submittedSubtitle: "We'll verify your views and add earnings within 24 hours.",
  },
  earnings: {
    title: 'Earnings',
    totalEarned: 'Total Earned',
    pending: 'Pending',
    available: 'Available to Withdraw',
    withdraw: 'Withdraw',
    history: 'Submission History',
    views: 'views',
    noSubmissions: 'No submissions yet.',
  },
  profile: {
    title: 'Profile',
    tiktok: 'TikTok',
    instagram: 'Instagram',
    payouts: 'Payout Settings',
    setupStripe: 'Set Up Payouts',
    stripeConnected: 'Payouts Connected',
    payoutHistory: 'Payout History',
    signOut: 'Sign Out',
    kycRequired: 'ID Verification Required',
    kycSubtitle: 'Required for payouts over $100.',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'No internet connection.',
    invalidPhone: 'Enter a valid phone number.',
    invalidCode: 'Invalid code. Please try again.',
    invalidUrl: 'Enter a valid TikTok or Instagram URL.',
  },
};
